# Generated by Django 5.0.7 on 2024-07-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='resto_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='resto_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='resto_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
